### ISSUE TITLE
Missing user_agents

### ISSUE THREAD

**Issue by waghanza** [Ayehavgunne/Cactuar#9]
Hi @Ayehavgunne,

Trying to install `Tonberry` with `python` **3.8**, I have
```python
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-epvctv2f/tonberry/setup.py'"'"'; __file__='"'"'/tmp/pip-install-epvctv2f/tonberry/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-epvctv2f/tonberry/pip-egg-info
         cwd: /tmp/pip-install-epvctv2f/tonberry/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-epvctv2f/tonberry/setup.py", line 2, in <module>
        from tonberry.__version__ import VERSION
      File "/tmp/pip-install-epvctv2f/tonberry/tonberry/__init__.py", line 4, in <module>
        from tonberry.contexted.request import Request
      File "/tmp/pip-install-epvctv2f/tonberry/tonberry/contexted/request.py", line 4, in <module>
        import user_agents
    ModuleNotFoundError: No module named 'user_agents'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
What is this module ?
https://github.com/Ayehavgunne/Tonberry/blob/ff888ee53a3e4fd6298d24ea07d8ac663b4e7e45/tonberry/contexted/request.py#L4

Regards,

**Comment by waghanza** [comment]
Working on **master**, btw.
The above code is for `v0.1.0`

**Comment by Ayehavgunne** [comment]
PyPI has version 0.2.1 available now and I think it corrects this issue. `user_agents` parses the user agent string into an easily accessible object. I have been thinking of making it optional though.

The master branch should be updated to the same status as what is on PyPI. Did you install using pip or through `python setup.py`?

**Comment by Ayehavgunne** [comment]
I just created a release of 0.2.1 here in GitHub since I forgot about that.
